CREATE TABLE [dbo].[GroupSprint]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[Date] DATETIME NOT NULL,
	[Status] NVARCHAR(200) NOT NULL DEFAULT 'Todo',
	[Remark] NVARCHAR(100) NOT NULL DEFAULT '',
	[CreatedOn] DATETIME NOT NULL,
	[ModifiedOn] DATETIME NOT NULL,
	[CreatedBy] NVARCHAR(200) NOT NULL DEFAULT '',
	[ModifiedBy] NVARCHAR(200) NOT NULL DEFAULT '',
	[GroupId] INT NOT NULL DEFAULT 0
)
