CREATE TABLE [dbo].[SprintScenario]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[SprintId] INT NOT NULL,
	[Title] VARCHAR(255) NOT NULL DEFAULT '',
	[Status] VARCHAR(255) NOT NULL DEFAULT 'Todo',
	[Priority] INT NOT NULL DEFAULT 0,
	[CreatedOn] DATETIME NOT NULL,
	[ModifiedOn] DATETIME NOT NULL,
	[CreatedBy] NVARCHAR(255) NOT NULL DEFAULT '',
	[ModifiedBy] NVARCHAR(255) NOT NULL DEFAULT '',
)
