CREATE TABLE [dbo].[Sentences]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[Sentence] VARCHAR(MAX) NOT NULL DEFAULT '',
	[Topic] VARCHAR(MAX) NOT NULL DEFAULT '',
	[InitId] INT NOT NULL DEFAULT 0,
)
